#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xBB5869F064EA74AB (chet@cwru.edu)
#
Name     : bash
Version  : 5.0
Release  : 51
URL      : https://mirrors.kernel.org/gnu/bash/bash-5.0.tar.gz
Source0  : https://mirrors.kernel.org/gnu/bash/bash-5.0.tar.gz
Source1  : https://mirrors.kernel.org/gnu/bash/bash-5.0.tar.gz.sig
Summary  : Bash headers for bash loadable builtins
Group    : Development/Tools
License  : GPL-3.0 GPL-3.0+
Requires: bash-bin = %{version}-%{release}
Requires: bash-info = %{version}-%{release}
Requires: bash-license = %{version}-%{release}
Requires: bash-locales = %{version}-%{release}
Requires: bash-man = %{version}-%{release}
BuildRequires : bison
BuildRequires : ncurses-dev
BuildRequires : util-linux
Patch1: bash50-001.patch
Patch2: bash50-002.patch
Patch3: bash50-003.patch
Patch4: bash50-004.patch
Patch5: bash50-005.patch
Patch6: bash50-006.patch
Patch7: bash50-007.patch
Patch8: bash50-008.patch
Patch9: bash50-009.patch
Patch10: bash50-010.patch
Patch11: bash50-011.patch
Patch12: bash50-012.patch
Patch13: bash50-013.patch
Patch14: bash50-014.patch
Patch15: bash50-015.patch
Patch16: bash50-016.patch
Patch17: nodlopen.patch
Patch18: stateless.patch
Patch19: 0001-Support-stateless-inputrc-configuration.patch

%description
Introduction
============
This is GNU Bash, version 5.0.  Bash is the GNU Project's Bourne
Again SHell, a complete implementation of the POSIX shell spec,
but also with interactive command line editing, job control on
architectures that support it, csh-like features such as history
substitution and brace expansion, and a slew of other features.
For more information on the features of Bash that are new to this
type of shell, see the file `doc/bashref.texi'.  There is also a
large Unix-style man page.  The man page is the definitive description
of the shell's features.

%package bin
Summary: bin components for the bash package.
Group: Binaries
Requires: bash-license = %{version}-%{release}

%description bin
bin components for the bash package.


%package doc
Summary: doc components for the bash package.
Group: Documentation
Requires: bash-man = %{version}-%{release}
Requires: bash-info = %{version}-%{release}

%description doc
doc components for the bash package.


%package extras
Summary: extras components for the bash package.
Group: Default

%description extras
extras components for the bash package.


%package info
Summary: info components for the bash package.
Group: Default

%description info
info components for the bash package.


%package license
Summary: license components for the bash package.
Group: Default

%description license
license components for the bash package.


%package locales
Summary: locales components for the bash package.
Group: Default

%description locales
locales components for the bash package.


%package man
Summary: man components for the bash package.
Group: Default

%description man
man components for the bash package.


%prep
%setup -q -n bash-5.0
cd %{_builddir}/bash-5.0
%patch1 -p0
%patch2 -p0
%patch3 -p0
%patch4 -p0
%patch5 -p0
%patch6 -p0
%patch7 -p0
%patch8 -p0
%patch9 -p0
%patch10 -p0
%patch11 -p0
%patch12 -p0
%patch13 -p0
%patch14 -p0
%patch15 -p0
%patch16 -p0
%patch17 -p1
%patch18 -p1
%patch19 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1581360985
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-lto -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-lto -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -Os -fdata-sections -ffunction-sections -fno-lto -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -Os -fdata-sections -ffunction-sections -fno-lto -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs=used "
%configure --disable-static --enable-cond-command --enable-history --enable-job-control --enable-readline --enable-extended-glob --enable-progcomp --enable-arith-for-command --enable-directory-stack --with-bash-malloc=no
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make check

%install
export SOURCE_DATE_EPOCH=1581360985
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/bash
cp %{_builddir}/bash-5.0/COPYING %{buildroot}/usr/share/package-licenses/bash/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/bash-5.0/lib/readline/COPYING %{buildroot}/usr/share/package-licenses/bash/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/bash-5.0/tests/COPYRIGHT %{buildroot}/usr/share/package-licenses/bash/771f6b3c33dd1c00e5d2f319cb801d0611ddd699
%make_install
%find_lang bash
## install_append content
ln -s bash %{buildroot}/usr/bin/sh
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/bash
/usr/bin/sh

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/bash/*

%files extras
%defattr(-,root,root,-)
/usr/bin/bashbug

%files info
%defattr(0644,root,root,0755)
/usr/share/info/bash.info

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/bash/771f6b3c33dd1c00e5d2f319cb801d0611ddd699
/usr/share/package-licenses/bash/8624bcdae55baeef00cd11d5dfcfa60f68710a02

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/bash.1
/usr/share/man/man1/bashbug.1

%files locales -f bash.lang
%defattr(-,root,root,-)

